import type {
  Agent,
  AgentPromptVersion,
  DebateSession,
  ICTConcept,
  LabState,
  MarketOutcome,
  PerformanceScore,
  PromptMutation,
  Recommendation,
  TradeThesis
} from "@/lib/types";
import { buildICTContext } from "@/lib/ict";
import { mockCandles } from "@/lib/mockData/mockCandles";
import { numericDate } from "@/lib/utils";

type AgentSeed = Omit<
  Agent,
  "currentPromptVersionId" | "confidenceHistory" | "currentSystemPrompt"
> & {
  prompt: string;
  historySeed: number[];
};

const promptGuardrail =
  "Operate in simulation only. Do not place orders, connect to brokers, or present financial advice.";

const agentSeeds: AgentSeed[] = [
  {
    id: "macro-rates",
    name: "Rates Agent",
    layer: "macro",
    domain: "rates",
    description: "Interprets yields, policy expectations, and curve pressure for index futures.",
    active: true,
    weight: 0.08,
    prompt: `${promptGuardrail} Track front-end rates, real yield pressure, curve steepening, and Fed repricing. Translate macro pressure into ES/NQ directional bias.`,
    confidence: 0.68,
    historySeed: [0.58, 0.6, 0.63, 0.64, 0.66, 0.68],
    hitRate: 0.61,
    wins: 14,
    losses: 9,
    drawdown: 0.07,
    sharpeLike: 1.18,
    confidenceCalibration: 0.82,
    tags: ["macro", "rates", "policy"]
  },
  {
    id: "macro-dollar",
    name: "Dollar Agent",
    layer: "macro",
    domain: "dollar",
    description: "Scores USD strength and its pressure on risk assets.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Evaluate DXY impulse, USD liquidity, and cross-asset dollar sensitivity before assigning futures bias.`,
    confidence: 0.62,
    historySeed: [0.54, 0.57, 0.61, 0.6, 0.63, 0.62],
    hitRate: 0.57,
    wins: 12,
    losses: 9,
    drawdown: 0.09,
    sharpeLike: 0.96,
    confidenceCalibration: 0.77,
    tags: ["macro", "usd", "liquidity"]
  },
  {
    id: "macro-volatility",
    name: "Volatility Agent",
    layer: "macro",
    domain: "volatility",
    description: "Reads implied volatility, realized range, and vol-control stress.",
    active: true,
    weight: 0.09,
    prompt: `${promptGuardrail} Weigh VIX term structure, realized range expansion, and gamma pressure. Penalize signals when volatility regime conflicts with trade location.`,
    confidence: 0.74,
    historySeed: [0.6, 0.62, 0.66, 0.7, 0.72, 0.74],
    hitRate: 0.66,
    wins: 19,
    losses: 10,
    drawdown: 0.05,
    sharpeLike: 1.42,
    confidenceCalibration: 0.88,
    tags: ["macro", "volatility", "gamma"]
  },
  {
    id: "macro-commodities",
    name: "Commodities Agent",
    layer: "macro",
    domain: "commodities",
    description: "Tracks energy and metals impulses that can alter index risk tone.",
    active: true,
    weight: 0.04,
    prompt: `${promptGuardrail} Assess crude, copper, and gold context for inflation, growth, and defensive flows before ranking index futures bias.`,
    confidence: 0.55,
    historySeed: [0.49, 0.51, 0.53, 0.56, 0.54, 0.55],
    hitRate: 0.52,
    wins: 10,
    losses: 9,
    drawdown: 0.11,
    sharpeLike: 0.62,
    confidenceCalibration: 0.7,
    tags: ["macro", "commodities", "inflation"]
  },
  {
    id: "macro-news-sentiment",
    name: "News Sentiment Agent",
    layer: "macro",
    domain: "news sentiment",
    description: "Turns simulated headlines and event risk into directional pressure.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Extract headline tone, surprise risk, and scheduled event hazard. Reduce confidence when the tape is event-driven but direction is unresolved.`,
    confidence: 0.6,
    historySeed: [0.51, 0.55, 0.56, 0.59, 0.58, 0.6],
    hitRate: 0.56,
    wins: 13,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.91,
    confidenceCalibration: 0.74,
    tags: ["macro", "news", "sentiment"]
  },
  {
    id: "market-session-levels",
    name: "Session Levels Agent",
    layer: "market_context",
    domain: "session levels",
    description: "Maps prior day/week/month, overnight, Globex, and opening-range levels for index futures liquidity.",
    active: true,
    weight: 0.08,
    prompt: `${promptGuardrail} Compare prior day high/low/close, prior week/month levels, overnight high/low, Globex range, and opening range. Determine whether an ICT sweep occurred at a meaningful futures liquidity level.`,
    confidence: 0.7,
    historySeed: [0.58, 0.61, 0.63, 0.66, 0.68, 0.7],
    hitRate: 0.63,
    wins: 18,
    losses: 10,
    drawdown: 0.06,
    sharpeLike: 1.24,
    confidenceCalibration: 0.82,
    tags: ["market context", "session levels", "futures"]
  },
  {
    id: "market-auction-volume-profile",
    name: "Auction/Volume Profile Agent",
    layer: "market_context",
    domain: "auction and volume profile",
    description: "Reads VWAP, anchored VWAP, VPOC, VAH, VAL, and mock acceptance/rejection context.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Evaluate VWAP, anchored VWAP, VPOC, VAH, VAL, and volume acceptance/rejection. Identify whether price is accepting or rejecting important auction levels.`,
    confidence: 0.68,
    historySeed: [0.55, 0.58, 0.61, 0.64, 0.66, 0.68],
    hitRate: 0.62,
    wins: 17,
    losses: 10,
    drawdown: 0.07,
    sharpeLike: 1.18,
    confidenceCalibration: 0.8,
    tags: ["market context", "auction", "volume profile"]
  },
  {
    id: "market-macro-event-risk",
    name: "Macro Event Risk Agent",
    layer: "macro",
    domain: "macro event risk",
    description: "Flags scheduled event risk that can distort normal ICT behavior.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Track FOMC, CPI, NFP, PPI, retail sales, Fed speakers, and event-time proximity. Warn when scheduled macro risk should cap confidence or pause normal ICT assumptions.`,
    confidence: 0.64,
    historySeed: [0.53, 0.56, 0.58, 0.61, 0.63, 0.64],
    hitRate: 0.58,
    wins: 14,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.98,
    confidenceCalibration: 0.76,
    tags: ["macro", "event risk", "futures"]
  },
  {
    id: "market-intermarket-confirmation",
    name: "Intermarket Confirmation Agent",
    layer: "market_context",
    domain: "intermarket confirmation",
    description: "Checks ES/NQ ratio, YM/ES divergence, VIX, DXY, yields, bonds, crude, and gold context.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Confirm or challenge the ES/NQ/MES/MNQ thesis using ES/NQ ratio, YM/ES divergence, VIX, DXY, 2-year and 10-year yields, bonds, crude, and gold risk context.`,
    confidence: 0.61,
    historySeed: [0.5, 0.53, 0.56, 0.58, 0.6, 0.61],
    hitRate: 0.56,
    wins: 13,
    losses: 10,
    drawdown: 0.09,
    sharpeLike: 0.88,
    confidenceCalibration: 0.73,
    tags: ["market context", "intermarket", "confirmation"]
  },
  {
    id: "market-positioning-gamma",
    name: "Positioning/Gamma Agent",
    layer: "market_context",
    domain: "positioning and gamma",
    description: "Provides higher-timeframe COT, put/call, gamma level, and dealer gamma flip context.",
    active: true,
    weight: 0.04,
    prompt: `${promptGuardrail} Review COT, put/call ratio, gamma levels, dealer gamma flip, and net positioning bias. Use this as higher-timeframe context only.`,
    confidence: 0.56,
    historySeed: [0.48, 0.5, 0.52, 0.54, 0.55, 0.56],
    hitRate: 0.53,
    wins: 11,
    losses: 10,
    drawdown: 0.1,
    sharpeLike: 0.72,
    confidenceCalibration: 0.69,
    tags: ["market context", "positioning", "gamma"]
  },
  {
    id: "market-volatility-regime-v2",
    name: "Volatility Regime Agent 2.0",
    layer: "market_context",
    domain: "volatility regime",
    description: "Uses VIX, ATR regime, range expansion, and realized volatility to adjust risk assumptions.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Use VIX, ATR regime, range expansion, and realized volatility to adjust confidence, stop assumptions, target expectations, and risk caution.`,
    confidence: 0.72,
    historySeed: [0.6, 0.63, 0.66, 0.69, 0.71, 0.72],
    hitRate: 0.65,
    wins: 19,
    losses: 10,
    drawdown: 0.05,
    sharpeLike: 1.39,
    confidenceCalibration: 0.86,
    tags: ["market context", "volatility", "risk regime"]
  },
  {
    id: "market-order-flow-planned",
    name: "Order Flow Agent",
    layer: "market_context",
    domain: "order flow",
    description: "Planned later layer for DOM, footprint, delta, cumulative delta, and large-print context.",
    active: false,
    weight: 0.02,
    prompt: `${promptGuardrail} Planned later: review DOM, footprint, delta, cumulative delta, and large prints for execution refinement only. Do not use this as core thesis evidence until data exists.`,
    confidence: 0.3,
    historySeed: [0.3, 0.3, 0.31, 0.3, 0.3, 0.3],
    hitRate: 0.5,
    wins: 0,
    losses: 0,
    drawdown: 0,
    sharpeLike: 0,
    confidenceCalibration: 0.5,
    tags: ["market context", "order flow", "planned"]
  },
  {
    id: "strategy-trend",
    name: "Trend Agent",
    layer: "strategy",
    domain: "trend",
    description: "Measures trend continuation and pullback quality.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Grade trend structure across timeframe alignment, pullback depth, and failed breakdowns. Avoid chasing after extended displacement.`,
    confidence: 0.69,
    historySeed: [0.57, 0.6, 0.62, 0.65, 0.68, 0.69],
    hitRate: 0.63,
    wins: 17,
    losses: 10,
    drawdown: 0.07,
    sharpeLike: 1.14,
    confidenceCalibration: 0.8,
    tags: ["strategy", "trend"]
  },
  {
    id: "strategy-mean-reversion",
    name: "Mean Reversion Agent",
    layer: "strategy",
    domain: "mean reversion",
    description: "Finds stretched moves back toward balance.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Identify stretched price, failed continuation, and balance re-entry. Require favorable location before suggesting reversal bias.`,
    confidence: 0.57,
    historySeed: [0.52, 0.54, 0.55, 0.57, 0.56, 0.57],
    hitRate: 0.55,
    wins: 12,
    losses: 10,
    drawdown: 0.09,
    sharpeLike: 0.73,
    confidenceCalibration: 0.72,
    tags: ["strategy", "mean reversion"]
  },
  {
    id: "strategy-breakout",
    name: "Breakout Agent",
    layer: "strategy",
    domain: "breakout",
    description: "Evaluates range compression, expansion, and failed breakouts.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Confirm range compression, volume proxy, displacement, and retest quality before endorsing breakout continuation.`,
    confidence: 0.61,
    historySeed: [0.53, 0.55, 0.59, 0.62, 0.6, 0.61],
    hitRate: 0.57,
    wins: 13,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.87,
    confidenceCalibration: 0.73,
    tags: ["strategy", "breakout", "range"]
  },
  {
    id: "strategy-liquidity",
    name: "Liquidity Agent",
    layer: "strategy",
    domain: "liquidity",
    description: "Marks resting liquidity, stops, and magnet levels.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Map prior highs/lows, overnight range, single prints, and resting liquidity. Estimate whether price is likely to seek or reject a liquidity pool.`,
    confidence: 0.72,
    historySeed: [0.59, 0.62, 0.66, 0.68, 0.71, 0.72],
    hitRate: 0.65,
    wins: 20,
    losses: 11,
    drawdown: 0.06,
    sharpeLike: 1.33,
    confidenceCalibration: 0.84,
    tags: ["strategy", "liquidity", "stops"]
  },
  {
    id: "strategy-risk-reward",
    name: "Risk/Reward Agent",
    layer: "strategy",
    domain: "risk/reward",
    description: "Rejects ideas with poor asymmetry or unclear invalidation.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Require clear entry zone, invalidation, target liquidity, and simulated risk/reward. Downgrade any thesis without a clean stop-risk narrative.`,
    confidence: 0.76,
    historySeed: [0.64, 0.67, 0.7, 0.72, 0.74, 0.76],
    hitRate: 0.68,
    wins: 21,
    losses: 10,
    drawdown: 0.04,
    sharpeLike: 1.61,
    confidenceCalibration: 0.9,
    tags: ["strategy", "risk", "validation"]
  },
  {
    id: "strategy-ict-market-structure",
    name: "ICT Market Structure Agent",
    layer: "strategy",
    domain: "ICT market structure",
    description: "Looks for break in structure, shift, and higher-timeframe bias.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Detect higher-timeframe bias, market structure shift, break in structure, and displacement. State when structure is too noisy for conviction.`,
    confidence: 0.73,
    historySeed: [0.61, 0.63, 0.67, 0.7, 0.72, 0.73],
    hitRate: 0.67,
    wins: 22,
    losses: 11,
    drawdown: 0.05,
    sharpeLike: 1.48,
    confidenceCalibration: 0.86,
    tags: ["strategy", "ict", "structure"]
  },
  {
    id: "strategy-ict-liquidity-sweep",
    name: "ICT Liquidity Sweep Agent",
    layer: "strategy",
    domain: "ICT liquidity sweep",
    description: "Identifies sweep, failure to continue, and reversal conditions.",
    active: true,
    weight: 0.07,
    prompt: `${promptGuardrail} Identify buy-side or sell-side liquidity sweeps, rejection quality, and follow-through. Do not call a sweep valid without displacement after the raid.`,
    confidence: 0.66,
    historySeed: [0.56, 0.58, 0.61, 0.64, 0.67, 0.66],
    hitRate: 0.58,
    wins: 15,
    losses: 11,
    drawdown: 0.12,
    sharpeLike: 0.84,
    confidenceCalibration: 0.68,
    tags: ["strategy", "ict", "liquidity sweep"]
  },
  {
    id: "strategy-ict-fair-value-gap",
    name: "ICT Fair Value Gap Agent",
    layer: "strategy",
    domain: "ICT fair value gap",
    description: "Scores displacement gaps and likely mitigation zones.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Detect fair value gaps created by displacement. Score whether mitigation is likely to hold, fail, or become a draw on liquidity.`,
    confidence: 0.64,
    historySeed: [0.52, 0.55, 0.58, 0.6, 0.63, 0.64],
    hitRate: 0.59,
    wins: 16,
    losses: 11,
    drawdown: 0.09,
    sharpeLike: 0.95,
    confidenceCalibration: 0.75,
    tags: ["strategy", "ict", "fvg"]
  },
  {
    id: "strategy-ict-session-timing",
    name: "ICT Session Timing Agent",
    layer: "strategy",
    domain: "ICT session timing",
    description: "Tags kill zones, session transitions, and time-based trap risk.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Tag Asia range, London open, NY AM, lunch, and NY PM context. Penalize entries outside a meaningful session timing edge.`,
    confidence: 0.7,
    historySeed: [0.58, 0.6, 0.63, 0.66, 0.69, 0.7],
    hitRate: 0.62,
    wins: 18,
    losses: 11,
    drawdown: 0.07,
    sharpeLike: 1.1,
    confidenceCalibration: 0.81,
    tags: ["strategy", "ict", "kill zone"]
  },
  {
    id: "strategy-grinch-htf-bias",
    name: "Higher-Timeframe Bias Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 HTF bias",
    description: "Classifies higher-timeframe bias and draw on liquidity from the active dealing range.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Use dealing range, premium/discount, previous highs/lows, and higher-timeframe liquidity precedence. Output bias only as research context.`,
    confidence: 0.63,
    historySeed: [0.52, 0.55, 0.58, 0.6, 0.62, 0.63],
    hitRate: 0.58,
    wins: 14,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.92,
    confidenceCalibration: 0.74,
    tags: ["strategy", "ict", "grinch", "htf bias"]
  },
  {
    id: "strategy-grinch-pd-hierarchy",
    name: "PD Array Hierarchy Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 PD hierarchy",
    description: "Ranks Sunday Open, 12AM Open, BPR, VI, FVG, breaker, mitigation, and order-block references.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Rank PD arrays by hierarchy and require respect before treating lower arrays as valid. Do not create trade instructions.`,
    confidence: 0.61,
    historySeed: [0.5, 0.53, 0.56, 0.58, 0.6, 0.61],
    hitRate: 0.56,
    wins: 13,
    losses: 10,
    drawdown: 0.09,
    sharpeLike: 0.86,
    confidenceCalibration: 0.72,
    tags: ["strategy", "ict", "grinch", "pd array"]
  },
  {
    id: "strategy-grinch-opening-price",
    name: "Opening Price Equilibrium Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 opening prices",
    description: "Tracks Sunday Open as weekly equilibrium and 12AM Open as daily equilibrium.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Treat Sunday Open and 12AM Open as strongest 1H-and-lower PD arrays. Use them as context only.`,
    confidence: 0.6,
    historySeed: [0.5, 0.52, 0.55, 0.57, 0.59, 0.6],
    hitRate: 0.55,
    wins: 12,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.82,
    confidenceCalibration: 0.71,
    tags: ["strategy", "ict", "grinch", "opening price"]
  },
  {
    id: "strategy-grinch-dealing-range",
    name: "Dealing Range Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 dealing range",
    description: "Measures meaningful A-B range, equilibrium, premium, and discount.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Start bias by identifying the current dealing range and whether price is in premium, discount, or equilibrium.`,
    confidence: 0.62,
    historySeed: [0.52, 0.54, 0.57, 0.59, 0.61, 0.62],
    hitRate: 0.57,
    wins: 13,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.88,
    confidenceCalibration: 0.73,
    tags: ["strategy", "ict", "grinch", "dealing range"]
  },
  {
    id: "strategy-grinch-market-cycle",
    name: "Market Cycle Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 market cycle",
    description: "Classifies consolidation, expansion, retracement, and reversal conditions.",
    active: true,
    weight: 0.04,
    prompt: `${promptGuardrail} Classify cycle state before profile interpretation. Penalize continuation if range violation implies reversal.`,
    confidence: 0.59,
    historySeed: [0.49, 0.51, 0.54, 0.56, 0.58, 0.59],
    hitRate: 0.54,
    wins: 11,
    losses: 10,
    drawdown: 0.1,
    sharpeLike: 0.75,
    confidenceCalibration: 0.69,
    tags: ["strategy", "ict", "grinch", "market cycle"]
  },
  {
    id: "strategy-grinch-model-one",
    name: "Model 1 / Power 3 OTE Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 Model 1",
    description: "Detects 12AM equilibrium, London accumulation, displacement, NY retracement, and continuation profile quality.",
    active: true,
    weight: 0.06,
    prompt: `${promptGuardrail} Observe Model 1 on 15m after bias exists. Require 5m/1m confirmation later; do not produce executable entries.`,
    confidence: 0.57,
    historySeed: [0.46, 0.49, 0.52, 0.54, 0.56, 0.57],
    hitRate: 0.52,
    wins: 10,
    losses: 9,
    drawdown: 0.11,
    sharpeLike: 0.68,
    confidenceCalibration: 0.66,
    tags: ["strategy", "ict", "grinch", "model 1"]
  },
  {
    id: "strategy-grinch-reversal-profile",
    name: "Reversal Profile Agent",
    layer: "strategy",
    domain: "Grinch Phase 2 Reversal Profile",
    description: "Detects failed London interaction with 12AM Open, NY reversal timing, first target, and continuation quality.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Detect the Reversal Profile from 12AM Open, London 2-3 behavior, NY 9:30-10 timing, first target back to 12AM, and continuation quality. Research-only.`,
    confidence: 0.56,
    historySeed: [0.45, 0.48, 0.51, 0.53, 0.55, 0.56],
    hitRate: 0.51,
    wins: 10,
    losses: 10,
    drawdown: 0.11,
    sharpeLike: 0.64,
    confidenceCalibration: 0.65,
    tags: ["strategy", "ict", "grinch", "reversal profile"]
  },
  {
    id: "strategy-grinch-time-price",
    name: "Time-Price Alignment Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 timing",
    description: "Grades London observation, NY setup, NY confirmation, delayed, and expired timing.",
    active: true,
    weight: 0.04,
    prompt: `${promptGuardrail} Grade timing as ideal, acceptable, early, late, or expired. Downgrade late and expired profiles.`,
    confidence: 0.6,
    historySeed: [0.5, 0.52, 0.55, 0.57, 0.59, 0.6],
    hitRate: 0.55,
    wins: 12,
    losses: 10,
    drawdown: 0.08,
    sharpeLike: 0.82,
    confidenceCalibration: 0.72,
    tags: ["strategy", "ict", "grinch", "timing"]
  },
  {
    id: "strategy-grinch-entry-confirmation",
    name: "Entry Confirmation Agent",
    layer: "strategy",
    domain: "Grinch Phase 1 entry confirmation",
    description: "Scores PD array respect, mean-threshold respect, displacement, MSS/BOS, FVG, and timing confirmation.",
    active: true,
    weight: 0.05,
    prompt: `${promptGuardrail} Confirm entry quality only after the profile exists. Do not issue orders, execution intent, or readiness overrides.`,
    confidence: 0.58,
    historySeed: [0.48, 0.5, 0.53, 0.55, 0.57, 0.58],
    hitRate: 0.53,
    wins: 11,
    losses: 10,
    drawdown: 0.1,
    sharpeLike: 0.74,
    confidenceCalibration: 0.68,
    tags: ["strategy", "ict", "grinch", "entry confirmation"]
  },
  {
    id: "cio-synthesis",
    name: "CIO Synthesis Agent",
    layer: "cio",
    domain: "decision layer",
    description: "Synthesizes all agent views into a research-only final thesis.",
    active: true,
    weight: 0.16,
    prompt: `${promptGuardrail} Synthesize macro, futures market context, strategy, and ICT evidence. Output bullish, bearish, or neutral with confidence, invalidation, target zone, risk notes, and reasoning summary.`,
    confidence: 0.75,
    historySeed: [0.62, 0.66, 0.69, 0.72, 0.74, 0.75],
    hitRate: 0.69,
    wins: 24,
    losses: 11,
    drawdown: 0.04,
    sharpeLike: 1.67,
    confidenceCalibration: 0.89,
    tags: ["cio", "synthesis", "research only"]
  }
];

const buildAgents = (): Agent[] =>
  agentSeeds.map((agent) => ({
    ...agent,
    currentPromptVersionId: `prompt_${agent.id}_v1`,
    currentSystemPrompt: agent.prompt,
    confidenceHistory: agent.historySeed.map((value, index) => ({
      date: numericDate(index - agent.historySeed.length + 1),
      value
    }))
  }));

const buildBasePromptVersions = (): AgentPromptVersion[] =>
  agentSeeds.map((agent) => ({
    id: `prompt_${agent.id}_v1`,
    agentId: agent.id,
    version: "1.0.0",
    prompt: agent.prompt,
    createdAt: numericDate(-21),
    mutationReason: "Initial simulation prompt",
    status: "active",
    approvedByUser: true,
    activatedAt: numericDate(-21)
  }));

const ictTags: ICTConcept[] = [
  "liquidity sweep",
  "market structure shift",
  "displacement",
  "fair value gap",
  "premium/discount",
  "session timing",
  "higher-timeframe bias",
  "kill-zone tagging"
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "rec_001",
    agentId: "strategy-ict-liquidity-sweep",
    symbol: "NQ",
    timeframe: "5m",
    bias: "bullish",
    confidence: 0.72,
    reasoning: "Sell-side liquidity under the London low was swept, then price displaced back through the range midpoint.",
    entryZone: [18862, 18878],
    invalidation: 18838,
    target: 18948,
    ictTags: ["liquidity sweep", "displacement", "kill-zone tagging"],
    createdAt: numericDate(-1),
    simulatedOutcomeId: "outcome_001",
    score: 0.81
  },
  {
    id: "rec_002",
    agentId: "macro-volatility",
    symbol: "ES",
    timeframe: "15m",
    bias: "neutral",
    confidence: 0.63,
    reasoning: "Realized range expanded faster than the simulated liquidity map, lowering continuation quality.",
    ictTags: ["session timing"],
    createdAt: numericDate(-2),
    simulatedOutcomeId: "outcome_002",
    score: 0.66
  },
  {
    id: "rec_003",
    agentId: "market-intermarket-confirmation",
    symbol: "NQ",
    timeframe: "5m",
    bias: "bullish",
    confidence: 0.69,
    reasoning: "ES/NQ, DXY/NQ, and VIX/equity relationships supported the NQ discount pullback thesis.",
    entryZone: [18810, 18832],
    invalidation: 18778,
    target: 18920,
    ictTags: ["premium/discount", "higher-timeframe bias"],
    createdAt: numericDate(-3),
    simulatedOutcomeId: "outcome_003",
    score: 0.74
  },
  {
    id: "rec_004",
    agentId: "strategy-breakout",
    symbol: "ES",
    timeframe: "15m",
    bias: "bearish",
    confidence: 0.58,
    reasoning: "Failed upside breakout into premium suggested a return to session balance.",
    entryZone: [5268, 5272],
    invalidation: 5281,
    target: 5244,
    ictTags: ["premium/discount", "market structure shift"],
    createdAt: numericDate(-4),
    simulatedOutcomeId: "outcome_004",
    score: 0.59
  },
  {
    id: "rec_005",
    agentId: "strategy-risk-reward",
    symbol: "MNQ",
    timeframe: "5m",
    bias: "neutral",
    confidence: 0.78,
    reasoning: "Target liquidity was too close to the proposed stop to justify directional research conviction.",
    ictTags: ["premium/discount"],
    createdAt: numericDate(-5),
    simulatedOutcomeId: "outcome_005",
    score: 0.83
  },
  {
    id: "rec_006",
    agentId: "cio-synthesis",
    symbol: "NQ",
    timeframe: "5m",
    bias: "bullish",
    confidence: 0.72,
    reasoning: "CIO composite favored a simulated long after sweep, displacement, session levels, and intermarket context aligned.",
    entryZone: [18864, 18880],
    invalidation: 18836,
    target: 18952,
    ictTags: ["liquidity sweep", "displacement", "higher-timeframe bias"],
    createdAt: numericDate(-1),
    simulatedOutcomeId: "outcome_001",
    score: 0.84
  }
];

export const mockOutcomes: MarketOutcome[] = [
  {
    id: "outcome_001",
    symbol: "NQ",
    timeframe: "5m",
    session: "New York AM",
    resolvedAt: numericDate(0),
    actualBias: "bullish",
    priceMove: 72,
    maxAdverseExcursion: 18,
    maxFavorableExcursion: 86,
    liquidityTargetReached: true,
    invalidationHit: false,
    notes: "Simulated target liquidity above the prior AM high was reached."
  },
  {
    id: "outcome_002",
    symbol: "ES",
    timeframe: "15m",
    session: "New York PM",
    resolvedAt: numericDate(-1),
    actualBias: "neutral",
    priceMove: 7,
    maxAdverseExcursion: 12,
    maxFavorableExcursion: 13,
    liquidityTargetReached: false,
    invalidationHit: false,
    notes: "Balanced trade stayed inside the afternoon range."
  },
  {
    id: "outcome_003",
    symbol: "NQ",
    timeframe: "5m",
    session: "London",
    resolvedAt: numericDate(-2),
    actualBias: "bullish",
    priceMove: 54,
    maxAdverseExcursion: 15,
    maxFavorableExcursion: 64,
    liquidityTargetReached: true,
    invalidationHit: false,
    notes: "Discount entry held before price repriced into buy-side liquidity."
  },
  {
    id: "outcome_004",
    symbol: "ES",
    timeframe: "15m",
    session: "New York AM",
    resolvedAt: numericDate(-3),
    actualBias: "bearish",
    priceMove: -22,
    maxAdverseExcursion: 9,
    maxFavorableExcursion: 29,
    liquidityTargetReached: true,
    invalidationHit: false,
    notes: "Failed breakout returned to the session midpoint and lower liquidity."
  },
  {
    id: "outcome_005",
    symbol: "MNQ",
    timeframe: "5m",
    session: "New York Lunch",
    resolvedAt: numericDate(-4),
    actualBias: "neutral",
    priceMove: -6,
    maxAdverseExcursion: 21,
    maxFavorableExcursion: 18,
    liquidityTargetReached: false,
    invalidationHit: true,
    notes: "Chop confirmed the risk/reward veto."
  }
];

const seededIctContext = buildICTContext(mockCandles, {
  symbol: "NQ",
  timeframe: "5m",
  session: "New York AM"
});

export const mockTradeTheses: TradeThesis[] = [
  {
    id: "thesis_001",
    symbol: "NQ",
    timeframe: "5m",
    session: "New York AM",
    marketRegime: "trend",
    notes: "Mock session: sweep of London low with session levels and intermarket context stable.",
    finalBias: "bullish",
    confidence: 0.72,
    thesisSummary: "Research thesis favors a simulated NQ long from discount after a sell-side sweep and displacement.",
    invalidationLevel: 18836,
    targetLiquidity: 18952,
    riskNotes: "Invalid if price accepts below the swept low or if volatility expands without upside displacement.",
    reasoningSummary: "Liquidity sweep, session timing, session levels, and intermarket confirmation aligned while risk/reward remained above 2R.",
    ictContext: seededIctContext,
    simulatedTradePlan: {
      id: "plan_001",
      symbol: "NQ",
      timeframe: "5m",
      bias: "bullish",
      entryZone: [18864, 18880],
      invalidation: 18836,
      targetLiquidity: 18952,
      stopRiskNotes: "Use the swept low as invalidation in simulation. No order execution.",
      riskReward: 2.3,
      mode: "simulation"
    },
    createdAt: numericDate(-1),
    disclaimer: "Research only. Simulation output, not financial advice."
  }
];

export const mockDebateSessions: DebateSession[] = [
  {
    id: "debate_001",
    createdAt: numericDate(-1),
    symbol: "NQ",
    timeframe: "5m",
    session: "New York AM",
    marketRegime: "trend",
    notes: "Mock session: sweep of London low with futures market context stable.",
    messages: [
      {
        id: "msg_001",
        agentId: "macro-volatility",
        agentName: "Volatility Agent",
        layer: "macro",
        stance: "bullish",
        confidence: 0.66,
        message: `Volatility is elevated but controlled; ICT confluence is ${Math.round(seededIctContext.confluenceScore * 100)}% with ${seededIctContext.displacement} displacement and ${seededIctContext.killZone} timing.`,
        ictTags: ["displacement", "session timing"],
        createdAt: numericDate(-1)
      },
      {
        id: "msg_002",
        agentId: "market-intermarket-confirmation",
        agentName: "Intermarket Confirmation Agent",
        layer: "market_context",
        stance: "bullish",
        confidence: 0.7,
        message: `Intermarket context is supportive while structured ICT bias is ${seededIctContext.bias}; latest swing high ${seededIctContext.latestSwingHigh?.price ?? "n/a"} remains the upside liquidity reference.`,
        ictTags: ["higher-timeframe bias"],
        createdAt: numericDate(-1)
      },
      {
        id: "msg_003",
        agentId: "strategy-ict-liquidity-sweep",
        agentName: "ICT Liquidity Sweep Agent",
        layer: "strategy",
        stance: "bullish",
        confidence: 0.72,
        message: `ICT sweep engine found ${seededIctContext.liquiditySweeps.length} sweep(s), ${seededIctContext.fairValueGaps.length} FVG(s), and ${seededIctContext.premiumDiscount} location during ${seededIctContext.killZone} timing.`,
        ictTags,
        createdAt: numericDate(-1)
      }
    ],
    recommendationIds: ["rec_001", "rec_006"],
    cioThesisId: "thesis_001"
  }
];

export const createInitialLabState = (): LabState => {
  const basePromptVersions = buildBasePromptVersions();
  const extraPromptVersions: AgentPromptVersion[] = [
    {
      id: "prompt_macro_volatility_v2",
      agentId: "macro-volatility",
      version: "1.1.0",
      prompt: `${promptGuardrail} Weigh VIX term structure, realized range expansion, gamma pressure, and whether volatility supports the proposed holding window before scoring continuation.`,
      createdAt: numericDate(-6),
      mutationReason: "Added holding-window volatility check after simulated chop.",
      status: "accepted",
      approvedByUser: true,
      activatedAt: numericDate(-5),
      supersedesVersionId: "prompt_macro-volatility_v1",
      performanceBefore: {
        hitRate: 0.59,
        drawdown: 0.08,
        sharpeLike: 0.98,
        confidenceCalibration: 0.74,
        sampleSize: 22
      },
      performanceAfter: {
        hitRate: 0.66,
        drawdown: 0.05,
        sharpeLike: 1.42,
        confidenceCalibration: 0.88,
        sampleSize: 29
      }
    },
    {
      id: "prompt_strategy_ict_liquidity_sweep_v2_candidate",
      agentId: "strategy-ict-liquidity-sweep",
      version: "1.1.0-candidate",
      prompt: `${promptGuardrail} Require a sweep, clear rejection, displacement through a reference level, and session kill-zone alignment before assigning confidence above 0.65.`,
      createdAt: numericDate(-1),
      mutationReason: "Weakest agent by calibration; tighten confirmation rules.",
      status: "candidate",
      approvedByUser: false,
      supersedesVersionId: "prompt_strategy-ict-liquidity-sweep_v1",
      performanceBefore: {
        hitRate: 0.58,
        drawdown: 0.12,
        sharpeLike: 0.84,
        confidenceCalibration: 0.68,
        sampleSize: 26
      }
    },
    {
      id: "prompt_market_intermarket_confirmation_v2_rejected",
      agentId: "market-intermarket-confirmation",
      version: "1.1.0-rejected",
      prompt: `${promptGuardrail} Overweight simulated intermarket confirmation above ICT structure and risk/reward evidence.`,
      createdAt: numericDate(-9),
      mutationReason: "Tested heavier intermarket weighting.",
      status: "rejected",
      approvedByUser: false,
      supersedesVersionId: "prompt_market-intermarket-confirmation_v1",
      performanceBefore: {
        hitRate: 0.56,
        drawdown: 0.09,
        sharpeLike: 0.88,
        confidenceCalibration: 0.73,
        sampleSize: 23
      },
      performanceAfter: {
        hitRate: 0.51,
        drawdown: 0.15,
        sharpeLike: 0.42,
        confidenceCalibration: 0.6,
        sampleSize: 12
      }
    }
  ];

  const agents = buildAgents().map((agent) =>
    agent.id === "macro-volatility"
      ? {
          ...agent,
          currentPromptVersionId: "prompt_macro_volatility_v2",
          currentSystemPrompt:
            extraPromptVersions.find((prompt) => prompt.id === "prompt_macro_volatility_v2")?.prompt ??
            agent.currentSystemPrompt
        }
      : agent
  );

  const promptMutations: PromptMutation[] = [
    {
      id: "mutation_001",
      agentId: "macro-volatility",
      fromPromptVersionId: "prompt_macro-volatility_v1",
      candidatePromptVersionId: "prompt_macro_volatility_v2",
      createdAt: numericDate(-6),
      reason: "Volatility signals were too early during range expansion.",
      proposedDiffSummary: "Added holding-window and gamma-pressure filters.",
      status: "accepted",
      requiresUserConfirmation: true,
      oldPerformance: {
        hitRate: 0.59,
        drawdown: 0.08,
        sharpeLike: 0.98,
        confidenceCalibration: 0.74,
        sampleSize: 22
      },
      candidatePerformance: {
        hitRate: 0.66,
        drawdown: 0.05,
        sharpeLike: 1.42,
        confidenceCalibration: 0.88,
        sampleSize: 29
      },
      userDecisionAt: numericDate(-5)
    },
    {
      id: "mutation_002",
      agentId: "strategy-ict-liquidity-sweep",
      fromPromptVersionId: "prompt_strategy-ict-liquidity-sweep_v1",
      candidatePromptVersionId: "prompt_strategy_ict_liquidity_sweep_v2_candidate",
      createdAt: numericDate(-1),
      reason: "Weakest current confidence calibration after simulated scoring.",
      proposedDiffSummary: "Requires sweep, rejection, displacement, and kill-zone alignment before high confidence.",
      status: "pending",
      requiresUserConfirmation: true,
      oldPerformance: {
        hitRate: 0.58,
        drawdown: 0.12,
        sharpeLike: 0.84,
        confidenceCalibration: 0.68,
        sampleSize: 26
      }
    },
    {
      id: "mutation_003",
      agentId: "market-intermarket-confirmation",
      fromPromptVersionId: "prompt_market-intermarket-confirmation_v1",
      candidatePromptVersionId: "prompt_market_intermarket_confirmation_v2_rejected",
      createdAt: numericDate(-9),
      reason: "Tested heavier intermarket confirmation weighting.",
      proposedDiffSummary: "Overweighted intermarket context and reduced ICT/risk confirmation.",
      status: "rejected",
      requiresUserConfirmation: true,
      oldPerformance: {
        hitRate: 0.56,
        drawdown: 0.09,
        sharpeLike: 0.88,
        confidenceCalibration: 0.73,
        sampleSize: 23
      },
      candidatePerformance: {
        hitRate: 0.51,
        drawdown: 0.15,
        sharpeLike: 0.42,
        confidenceCalibration: 0.6,
        sampleSize: 12
      },
      userDecisionAt: numericDate(-8)
    }
  ];

  const performanceScores: PerformanceScore[] = agents.map((agent) => ({
    id: `perf_${agent.id}`,
    agentId: agent.id,
    createdAt: numericDate(0),
    window: "30d",
    hitRate: agent.hitRate,
    drawdown: agent.drawdown,
    sharpeLike: agent.sharpeLike,
    confidenceCalibration: agent.confidenceCalibration,
    sampleSize: agent.wins + agent.losses,
    averageRecommendationScore: Math.min(0.95, agent.hitRate * 0.7 + agent.confidenceCalibration * 0.3)
  }));

  return {
    agents,
    promptVersions: [...basePromptVersions, ...extraPromptVersions],
    recommendations: mockRecommendations,
    outcomes: mockOutcomes,
    performanceScores,
    promptMutations,
    debateSessions: mockDebateSessions,
    tradeTheses: mockTradeTheses,
    handoffExports: [],
    advisoryPackets: [],
    advisoryResponses: [],
    userApprovals: [
      {
        id: "approval_001",
        createdAt: numericDate(-5),
        entityType: "prompt_mutation",
        entityId: "mutation_001",
        decision: "approved"
      },
      {
        id: "approval_002",
        createdAt: numericDate(-8),
        entityType: "prompt_mutation",
        entityId: "mutation_003",
        decision: "rejected"
      }
    ]
  };
};
